AWSTemplateFormatVersion: 2010-09-09

Description: Setup State Machine

Parameters:
  RoleStackName:
    Description: "Stack that deploys roles for genomic workflow"
    Type: String

Resources:
  GenomicWorkflow:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn:
        Fn::ImportValue: !Sub "${RoleStackName}:StatesExecutionRole"
      DefinitionString: !Sub |-
        {
           "Comment":"A simple example that submits a Job to AWS Batch",
           "StartAt":"RunPreQCandTrimJob",
            "States": {
               "RunPreQCandTrimJob": {
                     "Type":"Parallel",
                     "Branches": [
                        {
                           "StartAt":"RunKraken",
                           "States": {
                                 "RunKraken": {
                                    "Type":"Task",
                                    "Resource":"arn:aws:states:::batch:submitJob.sync",
                                    "Parameters": {
                                       "JobDefinition":"Kraken",
                                       "JobName.$":"$.kraken.JobName",
                                       "JobQueue":"ScLowPriority",
                                       "Parameters.$":"$.kraken"
                                    },
                                    "TimeoutSeconds": 3600,
                                    "InputPath":"$",
                                    "ResultPath":"$.krakenOut",
                                    "Retry": [
                                       {
                                             "ErrorEquals": [
                                                "States.Timeout"
                                             ],
                                             "IntervalSeconds": 3,
                                             "MaxAttempts": 2,
                                             "BackoffRate": 1.5
                                       }
                                    ],
                                    "End": true
                                 }
                           }
                        },
                        {
                           "StartAt":"RunPreQC",
                           "States": {
                                 "RunPreQC": {
                                    "Type":"Task",
                                    "Resource":"arn:aws:states:::batch:submitJob.sync",
                                    "Parameters": {
                                       "JobDefinition":"PreQC",
                                       "JobName.$":"$.preQC.JobName",
                                       "JobQueue":"ScLowPriority",
                                       "Parameters.$":"$.preQC"
                                    },
                                    "TimeoutSeconds": 7200,
                                    "InputPath":"$",
                                    "ResultPath":"$.preQCout",
                                    "Retry": [
                                       {
                                             "ErrorEquals": [
                                                "States.Timeout"
                                             ],
                                             "IntervalSeconds": 3,
                                             "MaxAttempts": 2,
                                             "BackoffRate": 1.5
                                       }
                                    ],
                                    "End": true
                                 }
                           }
                        },
                        {
                           "StartAt":"RunTrimGalore",
                           "States": {
                                 "RunTrimGalore": {
                                    "Type":"Task",
                                    "Resource":"arn:aws:states:::batch:submitJob.sync",
                                    "Parameters": {
                                       "JobDefinition":"TrimGalore",
                                       "JobName.$":"$.trimgalore.JobName",
                                       "JobQueue":"ScLowPriority",
                                       "Parameters.$":"$.trimgalore"
                                    },
                                    "TimeoutSeconds": 3600,
                                    "Next":"RunSpades",
                                    "InputPath":"$",
                                    "ResultPath":"$.trimgaloreOut",
                                    "Retry": [
                                       {
                                             "ErrorEquals": [
                                                "States.Timeout"
                                             ],
                                             "IntervalSeconds": 3,
                                             "MaxAttempts": 2,
                                             "BackoffRate": 1.5
                                       }
                                    ]
                                 },
                                 "RunSpades": {
                                    "Type":"Task",
                                    "Resource":"arn:aws:states:::batch:submitJob.sync",
                                    "Parameters": {
                                       "JobDefinition":"Spades",
                                       "JobName.$":"$.spades.JobName",
                                       "JobQueue":"ScLowPriority",
                                       "Parameters.$":"$.spades"
                                    },
                                    "TimeoutSeconds": 3600,
                                    "Next":"RunBusco",
                                    "InputPath":"$",
                                    "ResultPath":"$.spadesOut",
                                    "Retry": [
                                       {
                                             "ErrorEquals": [
                                                "States.Timeout"
                                             ],
                                             "IntervalSeconds": 3,
                                             "MaxAttempts": 2,
                                             "BackoffRate": 1.5
                                       }
                                    ]
                                 },
                                 "RunBusco": {
                                    "Type":"Task",
                                    "Resource":"arn:aws:states:::batch:submitJob.sync",
                                    "Parameters": {
                                       "JobDefinition":"Busco",
                                       "JobName.$":"$.busco.JobName",
                                       "JobQueue":"ScLowPriority",
                                       "Parameters.$":"$.busco"
                                    },
                                    "TimeoutSeconds": 3600,
                                    "InputPath":"$",
                                    "ResultPath":"$.buscoOut",
                                    "Retry": [
                                       {
                                             "ErrorEquals": [
                                                "States.Timeout"
                                             ],
                                             "IntervalSeconds": 3,
                                             "MaxAttempts": 2,
                                             "BackoffRate": 1.5
                                       }
                                    ],
                                    "End": true
                                 }
                           }
                        }
                     ],
                     "End": true
               }
            }
         }
Outputs:
  GenomicsWorkflowArn:
    Description: GenomicWorkflow ARN
    Value: !Ref GenomicWorkflow
  StackName:
    Description: StackName
    Value: !Sub ${AWS::StackName}
